# Site settings
title: matt battison
description: >-
  I'm Matt. In my day job I'm a software engineer in London. Here I write about things that I find interesting - YMMV.

# Social media
email: hello@mattbattison.dev
twitter_username: mattbattison
github_username:  mattbattison
instagram_username: mattbattison

# Build settings
markdown: kramdown
theme: minima

# Plugins
plugins:
  - jekyll-feed

# Excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
